version: '3'

services:
  db:
    environment:
      MYSQL_DATABASE: musiqueapproximative
      MYSQL_ROOT_PASSWORD: root
    image: mysql:5.7.25
    platform: linux/amd64
    volumes:
      - ./var/db:/var/lib/mysql
      - ./src/data/fixtures/musiqueapproximative.sql:/docker-entrypoint-initdb.d/00_musiqueapproximative.sql

  php:
    build: .
    command: [/bin/sh, -c, make configure && composer install && php -S 0.0.0.0:8000 -t web]
    depends_on:
      - db
    ports:
      - 8001:8000
    volumes:
      - ./src:/usr/local/src
      - ./etc/${PROFILE-musiqueapproximative.localhost}/.env:/usr/local/src/.env
