<?php

/**
 * UserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    musique-approximative
 * @subpackage model
 * @author     Tristan Rivoallan <tristan@rivoallan.net>
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
class UserProfile extends BaseUserProfile
{
}
