<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $first_name
 * @property string $last_name
 * @property string $facebook_uid
 * @property string $email
 * @property string $email_hash
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer            getUserId()       Returns the current record's "user_id" value
 * @method string             getFirstName()    Returns the current record's "first_name" value
 * @method string             getLastName()     Returns the current record's "last_name" value
 * @method string             getFacebookUid()  Returns the current record's "facebook_uid" value
 * @method string             getEmail()        Returns the current record's "email" value
 * @method string             getEmailHash()    Returns the current record's "email_hash" value
 * @method sfGuardUser        getSfGuardUser()  Returns the current record's "sfGuardUser" value
 * @method sfGuardUserProfile setUserId()       Sets the current record's "user_id" value
 * @method sfGuardUserProfile setFirstName()    Sets the current record's "first_name" value
 * @method sfGuardUserProfile setLastName()     Sets the current record's "last_name" value
 * @method sfGuardUserProfile setFacebookUid()  Sets the current record's "facebook_uid" value
 * @method sfGuardUserProfile setEmail()        Sets the current record's "email" value
 * @method sfGuardUserProfile setEmailHash()    Sets the current record's "email_hash" value
 * @method sfGuardUserProfile setSfGuardUser()  Sets the current record's "sfGuardUser" value
 * 
 * @package    musique-approximative
 * @subpackage model
 * @author     Tristan Rivoallan <tristan@rivoallan.net>
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('first_name', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('last_name', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('facebook_uid', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('email_hash', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));


        $this->index('facebook_uid_index', array(
             'fields' => 
             array(
              0 => 'facebook_uid',
             ),
             'unique' => true,
             ));
        $this->index('email_index', array(
             'fields' => 
             array(
              0 => 'email',
             ),
             'unique' => true,
             ));
        $this->index('email_hash_index', array(
             'fields' => 
             array(
              0 => 'email_hash',
             ),
             'unique' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}