<?php

/**
 * BasePost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $body
 * @property string $track_title
 * @property string $track_author
 * @property string $track_filename
 * @property string $track_md5
 * @property string $buy_url
 * @property integer $svn_revision
 * @property datetime $publish_on
 * @property boolean $is_online
 * @property integer $contributor_id
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer     getId()             Returns the current record's "id" value
 * @method string      getBody()           Returns the current record's "body" value
 * @method string      getTrackTitle()     Returns the current record's "track_title" value
 * @method string      getTrackAuthor()    Returns the current record's "track_author" value
 * @method string      getTrackFilename()  Returns the current record's "track_filename" value
 * @method string      getTrackMd5()       Returns the current record's "track_md5" value
 * @method string      getBuyUrl()         Returns the current record's "buy_url" value
 * @method integer     getSvnRevision()    Returns the current record's "svn_revision" value
 * @method datetime    getPublishOn()      Returns the current record's "publish_on" value
 * @method boolean     getIsOnline()       Returns the current record's "is_online" value
 * @method integer     getContributorId()  Returns the current record's "contributor_id" value
 * @method sfGuardUser getSfGuardUser()    Returns the current record's "sfGuardUser" value
 * @method Post        setId()             Sets the current record's "id" value
 * @method Post        setBody()           Sets the current record's "body" value
 * @method Post        setTrackTitle()     Sets the current record's "track_title" value
 * @method Post        setTrackAuthor()    Sets the current record's "track_author" value
 * @method Post        setTrackFilename()  Sets the current record's "track_filename" value
 * @method Post        setTrackMd5()       Sets the current record's "track_md5" value
 * @method Post        setBuyUrl()         Sets the current record's "buy_url" value
 * @method Post        setSvnRevision()    Sets the current record's "svn_revision" value
 * @method Post        setPublishOn()      Sets the current record's "publish_on" value
 * @method Post        setIsOnline()       Sets the current record's "is_online" value
 * @method Post        setContributorId()  Sets the current record's "contributor_id" value
 * @method Post        setSfGuardUser()    Sets the current record's "sfGuardUser" value
 * 
 * @package    musique-approximative
 * @subpackage model
 * @author     Tristan Rivoallan <tristan@rivoallan.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('post');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('track_title', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('track_author', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('track_filename', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('track_md5', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('buy_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('svn_revision', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('publish_on', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
        $this->hasColumn('is_online', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('contributor_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'contributor_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'track_author',
              1 => 'track_title',
             ),
             'canUpdate' => true,
             ));
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'track_author',
              1 => 'track_title',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
        $this->actAs($searchable0);
    }
}