<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsfguarduserprofile extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sf_guard_user_profile', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'first_name' => 
             array(
              'type' => 'string',
              'length' => 30,
             ),
             'last_name' => 
             array(
              'type' => 'string',
              'length' => 30,
             ),
             'facebook_uid' => 
             array(
              'type' => 'string',
              'length' => 20,
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'email_hash' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
              'facebook_uid_index' => 
              array(
              'fields' => 
              array(
               0 => 'facebook_uid',
              ),
              'unique' => true,
              ),
              'email_index' => 
              array(
              'fields' => 
              array(
               0 => 'email',
              ),
              'unique' => true,
              ),
              'email_hash_index' => 
              array(
              'fields' => 
              array(
               0 => 'email_hash',
              ),
              'unique' => true,
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('sf_guard_user_profile');
    }
}