<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addpostindex extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('post_index', array(
             'keyword' => 
             array(
              'type' => 'string',
              'length' => 200,
              'primary' => true,
             ),
             'field' => 
             array(
              'type' => 'string',
              'length' => 50,
              'primary' => true,
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'primary' => true,
             ),
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'primary' => true,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'keyword',
              1 => 'field',
              2 => 'position',
              3 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('post_index');
    }
}