<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adduserprofile extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('user_profile', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'display_name' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'website_url' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
              'email_index' => 
              array(
              'fields' => 
              array(
               0 => 'email',
              ),
              'unique' => true,
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
        $this->createForeignKey('user_profile', 'user_profile_user_id_sf_guard_user_id', array(
             'name' => 'user_profile_user_id_sf_guard_user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => NULL,
             'onDelete' => 'cascade',
             ));
    }

    public function postUp()
    {
      $profiles = array(
        1 => array(
          'display_name' => 'Michel Bertier',
          'email'        => 'mbertier@parishq.net',
          'website_url'  => 'http://bertier.pastis-hosting.net'),
        2 => array(
          'display_name' => 'Puyo Puyo',
          'email'        => 'puyopuyo@wanadoo.fr',
          'website_url'  => 'http://puyopuyo.lautre.net'),
        3 => array(
          'display_name' => 'Glafouk',
          'email'        => 'glafouk@hotmail.com',
          'website_url'  => 'http://www.glafouk.com'),
        4 => array(
          'display_name' => 'Deehowyou',
          'email'        => 'deehowyou@gmail.com',
          'website_url'  => 'http://myspace.com/deehowyou'),
        5 => array(
          'display_name' => 'Edmond Leprince',
          'email'        => 'yan@egotwister.com',
          'website_url'  => 'http://www.egotwister.com'),
        6 => array(
          'display_name' => 'Chaton Pute',
          'email'        => 'sammyszx@gmail.com',
          'website_url'  => 'http://myspace.com/renardocrew'),
        7 => array(
          'display_name' => 'Bozoo',
          'email'        => 'bozoorak@gmail.com',
          'website_url'  => 'http://bozoo.pastis-hosting.net'),
        8 => array(
          'display_name' => 'Eat Rabbit',
          'email'        => 'yvanbabillon@gmail.com',
          'website_url'  => 'http://myspace.com/eatrabbit'),
        9 => array(
          'display_name' => 'Superpromotion',
          'email'        => 'huertasthibault@yahoo.fr',
          'website_url'  => 'http://myspace.com/renardocrew'),
        10 => array(
          'display_name' => 'Plancton9',
          'email'        => 'plancton9@gmail.com',
          'website_url'  => 'http://www.myspace.com/plancton9'),
        11 => array(
          'display_name' => 'Jacques Cochise',
          'email'        => 'misfits1@hotmail.fr',
          'website_url'  => 'http://www.cochise.canalblog.com'),
        12 => array(
          'display_name' => 'Valkiri',
          'email'        => 'val_kiri@msn.com',
          'website_url'  => 'http://www.ouiedire.net'),
        13 => array(
          'display_name' => 'Jambonbill',
          'email'        => 'jambonbill@gmail.com',
          'website_url'  => 'http://www.sidabitball.com'),
        14 => array(
          'display_name' => 'Schling',
          'email'        => 'samuel.douaud@gmail.com',
          'website_url'  => 'http://www.myspace.com/schling'),
        15 => array(
          'display_name' => 'Bibi Mati',
          'email'        => 'f.laugeois@gmail.com',
          'website_url'  => 'http://www.myspace.com/rachitikdata'),
        16 => array(
          'display_name' => 'Otrox',
          'email'        => 'otro@ilbm.info',
          'website_url'  => 'http://ilbm.info'),
        17 => array(
          'display_name' => 'Sascii',
          'email'        => 'sylvie@dokidoki.fr',
          'website_url'  => 'http://www.myspace.com/dokidokiparis'),
        18 => array(
          'display_name' => 'Santaklausnihil',
          'email'        => '',
          'website_url'  => 'http://www.musikmekanikcirkus.org'),
        19 => array(
          'display_name' => 'Gumbi',
          'email'        => 'gumbi_1@hotmail.fr',
          'website_url'  => 'http://www.flickr.com/photos/fredericbailleul/')
      );

      foreach ($profiles as $id => $profile)
      {
        if (Doctrine_Core::getTable('sfGuardUser')->find($id))
        {
          $user_profile = new UserProfile();
          $user_profile->user_id = $id;
          $user_profile->display_name = $profile['display_name'];
          $user_profile->email = $profile['email'];
          $user_profile->website_url = $profile['website_url'];
          $user_profile->save();
        }
      }
    }

    public function down()
    {
        $this->dropTable('user_profile');
        $this->dropForeignKey('user_profile', 'user_profile_user_id_sf_guard_user_id');
    }
}
