<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addpost extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('post', array(
             'id' => 
             array(
              'type' => 'integer',
              'autoincrement' => true,
              'primary' => true,
              'length' => 8,
             ),
             'body' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'track_title' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'track_author' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'track_filename' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'track_md5' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'svn_revision' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'publish_on' => 
             array(
              'type' => 'datetime',
              'notnull' => true,
              'length' => NULL,
             ),
             'is_online' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'contributor_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
              'post_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('post');
    }
}