<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('post', 'buy_url', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('post', 'buy_url');
    }
}