bleu_title:
  javascripts:
    directories: [bleu/javascripts]
    extensions: [js]
  stylesheets:
    directories: [bleu/stylesheets]
    extensions: [css]
  rules:
    mode: OR
    module: post
    query:
      title:
        regex: /.*bleu.*/i

bleu_artist:
  javascripts:
    directories: [bleu/javascripts]
    extensions: [js]
  stylesheets:
    directories: [bleu/stylesheets]
    extensions: [css]
  rules:
    mode: OR
    module: post
    query:
      artist:
        regex: /.*bleu.*/i

rouge_title:
  javascripts:
    directories: [rouge/javascripts]
    extensions: [js]
  stylesheets:
    directories: [rouge/stylesheets]
    extensions: [css]
  rules:
    mode: OR
    module: post
    query:
      title:
        regex: /.*rouge.*/i

rouge_artist:
  javascripts:
    directories: [rouge/javascripts]
    extensions: [js]
  stylesheets:
    directories: [rouge/stylesheets]
    extensions: [css]
  rules:
    mode: OR
    module: post
    query:
      artist:
        regex: /.*rouge.*/i
