bleu_title:
  javascripts:
    directories: [bleu_title/javascripts]
    extensions: [js]
  stylesheets:
    directories: [bleu_title/stylesheets]
    extensions: [css]
  rules:
    mode: OR
    module: post
    query:
      title:
        regex: /.*bleu.*/i

bleu_artist:
  javascripts:
    directories: [bleu_artist/javascripts]
    extensions: [js]
  stylesheets:
    directories: [bleu_artist/stylesheets]
    extensions: [css]
  rules:
    mode: OR
    module: post
    query:
      artist:
        regex: /.*bleu.*/i
