bleu_title:
  javascripts:
    directories: [bleu_title/javascripts]
    extensions: [js]
  stylesheets:
    directories: [bleu_title/stylesheets]
    extensions: [css]
  rules:
    query:
      title:
        regex: /.*bleu.*/i

bleu_artist:
  javascripts:
    directories: [bleu_artist/javascripts]
    extensions: [js]
  stylesheets:
    directories: [bleu_artist/stylesheets]
    extensions: [css]
  rules:
    query:
      artist:
        regex: /.*bleu.*/i

amour:
  javascripts:
    directories: [amour/javascript]
    extensions: [js]
  stylesheets:
    directories: [amour/stylesheets]
    extensions: [css]
  rules:
    query:
      title:
        regex: /.*(amour|love).*/i

robot:
  javascripts:
    directories: [robot/javascript]
    extensions: [js]
  stylesheets:
    directories: [robot/stylesheets]
    extensions: [css]
  rules:
    query:
      title:
        regex: /.*robot.*/i

fish:
  javascripts:
    directories: [fish/javascript]
    extensions: [js]
  stylesheets:
    directories: [fish/stylesheets]
    extensions: [css]
  rules:
    query:
      title:
        regex: /.*(fish|poisson).*/i

noir:
  javascripts:
    directories: [noir/javascript]
    extensions: [js]
  stylesheets:
    directories: [noir/stylesheets]
    extensions: [css]
  rules:
    query:
      title:
        regex: /.*(noir|black).*/i

light:
  javascripts:
    directories: [light/javascript]
    extensions: [js]
  stylesheets:
    directories: [light/stylesheets]
    extensions: [css]
  rules:
    query:
      title:
        regex: /.*(light|lumière).*/i

mort:
  javascripts:
    directories: [mort/javascript]
    extensions: [js]
  stylesheets:
    directories: [mort/stylesheets]
    extensions: [css]
  rules:
    query:
      title:
        regex: /.*(morte?s?|death?s|dead).*/i

